version: 2
build:
  os: "ubuntu-lts-latest"
  tools:
    python: "latest"

python:
  # add our extra requirements so we can use markdown
  install:
    - requirements: docs/requirements.txt

# build the docs with sphinx
# https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
sphinx:
  configuration: docs/conf.py
